  database-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{ github.workspace }}/database-files
      - run: mkdir -p ./datamodel
      - uses: gvenzl/setup-oracle-free@v1
        with:
          app-user: test
          app-user-password: test
          volume: ${{ github.workspace }}/database-files
          setup-scripts: ./datamodel
      - uses: gvenzl/setup-oracle-sqlcl@v1
      # Connect to the database and run a SQL command
      - name: Run SQLcl
        run: |
          echo "SELECT country_code, official_name, population \
          FROM countries WHERE name = 'Austria';" \
          | sql test/test@localhost/FREEPDB1
